# Two ArgoCD Application resources in one file (keeps intent, but uses the GHCR repo and safer parameter values)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JJ8817/Hello-world-argo-app.git
    targetRevision: HEAD
    path: helm/hello-world
    helm:
      valueFiles:
        - values-staging.yaml
      parameters:
        - name: image.tag
          value: f3813793cac9e041432d4f31c3e931cfc793c9c5
        - name: image.repository
          value: ghcr.io/jj8817/hello-world-flask
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JJ8817/Hello-world-argo-app.git
    targetRevision: HEAD
    path: helm/hello-world
    helm:
      valueFiles:
        - values-prod.yaml
      parameters:
        - name: image.tag
          value: f3813793cac9e041432d4f31c3e931cfc793c9c5
        - name: image.repository
          value: ghcr.io/jj8817/hello-world-flask
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
